---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}"
spec:
  replicas: {{ .Values.resources.replicas }}
  selector:
    matchLabels:
      type: infra
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        type: infra
        app: {{ .Chart.Name }}
      annotations:
        checksum/metrics-config: {{ include (print $.Template.BasePath "/config.metrics.yml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
          envFrom:
            - configMapRef:
                name: {{.Chart.Name}}-metrics
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: yeencloud.io/nodetype
                    operator: In
                    values:
                      - compute