---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}"
spec:
  replicas: {{ .Values.resources.replicas }}
  selector:
    matchLabels:
      type: infra
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        type: infra
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{.Values.image.repository}}:{{.Values.image.tag}}"
          envFrom:
            - configMapRef:
                name: {{.Chart.Name}}